### ISSUE TITLE
jamie:premium API

### ISSUE THREAD

**Issue by ozdaldogru** [ozdaldogru/Las-Vegas-Trip-Organizer#1]

**Comment by CryptoGymFreak** [comment]
link for carousel Premium package food 
https://bellagio.mgmresorts.com/en/restaurants/picasso.html

image:
https://static.mgmresorts.com/content/dam/MGM/bellagio/dining/picasso/food-and-drink/bellagio-restaurants-picasso-sauteed-filet-of-new-zealand-tai-snapper.tif.image.892.668.high.jpg

link for food in premium:
https://www.wynnlasvegas.com/dining/fine-dining/sw-steakhouse
 
image of cooking:
![image](https://github.com/ozdaldogru/Las-Vegas-Trip-Organizer/assets/142119845/38cabab1-815f-4c98-8605-12857e51c3ba)
https://th.bing.com/th/id/OIP.2SSEvdiXAIGjC0SJJTgGHwHaE_?w=251&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7

link for food in premium Ceasers Palace:
https://www.caesars.com/caesars-palace/restaurants/nobu

image of nobu:
![image](https://github.com/ozdaldogru/Las-Vegas-Trip-Organizer/assets/142119845/66afabb0-9cab-4196-91c1-909db7805637)

another image food link of nobu:
https://th.bing.com/th/id/OIP.4jai4MoIiYYa0CBwG6lm8QHaE8?w=237&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7

personal security:
https://swaysecurity.com/las-vegas-bodyguard-services/

image of sway security:
https://swaysecurity.com/wp-content/uploads/2017/06/bodyguard-pic.jpg

personal security:
https://www.ppgsecurity.com/services

ppg security image:
https://lirp.cdn-website.com/2f8781f9/dms3rep/multi/opt/8AC99A5F-CFCF-451C-8EDE-1DE9A8F18488-1920w.jpeg

travel companion site:
https://www.gogaffl.com/find-a-travel-buddy/las-vegas

high stakes gambling:
https://www.cosmopolitanlasvegas.com/

high stakes Gambling:
https://www.caesars.com/


high stakes image:
![image](https://github.com/ozdaldogru/Las-Vegas-Trip-Organizer/assets/142119845/51945abd-3a73-424a-93e4-01ea09b7dd90)

High Stakes img:
![image](https://github.com/ozdaldogru/Las-Vegas-Trip-Organizer/assets/142119845/d180339a-735d-4e4f-a35f-7ae8cec5c0ee)
