### ISSUE TITLE
folders need to be sorted

### ISSUE THREAD

**Issue by harrymac1972** [ozdaldogru/Las-Vegas-Trip-Organizer#10]
I'm scared to touch it now.... BUT... I think we should have folders: 'css' ,'js', 'imgs' inside assets.  And all images moved into 'imgs' folder.

**Comment by ozdaldogru** [comment]
> I'm scared to touch it now.... BUT... I think we should have folders: 'css' ,'js', 'imgs' inside assets. And all images moved into 'imgs' folder.

I'll do it in a min

**Comment by ozdaldogru** [comment]
folders and files locations re-organized.
