### ISSUE TITLE
julio: basic Api search

### ISSUE THREAD

**Issue by ozdaldogru** [ozdaldogru/Las-Vegas-Trip-Organizer#2]

**Comment by juniortotep** [comment]
https://rapidapi.com/devXprite/api/city-and-state-search-api/ 
https://rapidapi.com/stefan.skliarov/api/Ticketmaster/ (api to find events in area)
https://rapidapi.com/googlecloud/api/google-maps-geocoding/ (google maps api)
https://rapidapi.com/apidojo/api/hotels4/ (hotels api)
https://rapidapi.com/3b-data-3b-data-default/api/airbnb13/ (airbnb api, not sure if we want to use airbnb)
https://rapidapi.com/flightera/api/flightera-flight-data/ (flight info, i may look into a different api)
https://rapidapi.com/DataCrawler/api/tripadvisor16/ (tripadvisor api)
https://opendataportal-lasvegas.opendata.arcgis.com/ (site and database of everything las vegas)
